### ISSUE TITLE
empty meta-program

### ISSUE THREAD

**Issue by metaspine** [carmonalab/GeneNMF#4]
Hi
could you please explain what is the meaning of "Dropped 1 empty meta-programs"
after i run 
geneNMF.metaprograms <- getMetaPrograms(geneNMF.programs,
                                        nprograms=12,
                                        max.genes=50,
                                        hclust.method="ward.D2",
                                        min.confidence=0.3)

**Comment by mass-a** [comment]
Hello,
the meta-programs are identified by clustering individual programs (as determined by NMF factorization of individual samples), and then determining a consensus set of genes (a "meta-program") that are consistently seen in a given cluster of programs. This is necessary because NMF is not deterministic and can return different solution depending on the initialization conditions.

It is likely that some weaker or noisier programs only appear in one run. The result is a cluster of weakly related programs with very low similarity, with no genes above a minimal confidence threshold (`min.confidence` parameter). These "empty" meta-programs are dropped from the GeneNMF solution, as in the case you reported.

Best
-m

**Comment by metaspine** [comment]
Is there any way to remove empty meta-program from the figure？
